version: '3.8'

services:
  web:
    container_name: hrd-conference-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
